### ISSUE TITLE
Error with rollup?

### ISSUE THREAD

**Issue by findborg** [Andorbal/svelte-router-example#1]
I keep getting this error when I try to run,  
`Error: Error transforming C:\wamp64\www\50\src\main.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information`
By the way I am glad that you started this,  I hope that we can get it working.

**Comment by findborg** [comment]
FYI,  I am getting the same error with your starter setup as well.  I will keep digging.

**Comment by Andorbal** [comment]
I'm guessing from your path that you're running on Windows?  I have to admit, I didn't test this on Windows :)  But I *can* verify that I get the same error when I do try running on my Windows machine, so I don't have to hit you with the "Works on my machine" line!  LOL

I'll take a look at what's going on.  I know I saw this error in Linux when I was initially getting things set up so hopefully it's nothing too major.

**Comment by Andorbal** [comment]
Looks like the rollup plugin I was using for ES2015 was no longer maintained and there had been changes since the newest version was released. So I removed the reference and manually configured babel (which was only a few extra lines). I *was* able to get this running on Windows, so let me know if it works for you!

**Comment by findborg** [comment]
I will try it out now

**Comment by findborg** [comment]
It is working!  Good job.

**Comment by findborg** [comment]
Oh wow,  I really like that once you build the routes,  you can use normal links to the pages.  That is way cool.

**Comment by Andorbal** [comment]
Thanks!  And I'm glad it's working for you.  I'm trying to model this after react-router, so I can't take *all* the credit :P
