### ISSUE TITLE
build folder is needed

### ISSUE THREAD

**Issue by oren** [Andorbal/svelte-router-example#4]
shouldn't the readme include another step - `mkdir build` ?

**Comment by Andorbal** [comment]
It's supposed to make that automatically if it doesn't already exist.  Is it not doing this for you?

**Comment by oren** [comment]
nope. i am on ubuntu. I don't know if that's the reason.

**Comment by Andorbal** [comment]
This should be fixed with the most recent commit.  Thanks for bringing it up!
