### ISSUE TITLE
'if else' not working properly with the router links

### ISSUE THREAD

**Issue by oren** [Andorbal/svelte-router-example#6]
I am not sure if it's a problem with the router or with svelte itself.

When I add if else like this:
```js
{{#if loggedIn}}
  <li><Link to='/home'>Home</Link></li>
{{else}}
  <li><Link to='/about/bob'>About <em>Bob</em></Link></li>
  <li><Link to='/about/alice'>About <strong>Alice</strong></Link></li>
{{/if}}
```

if `loggedIn` is false I expect to see 'About Bob' and 'About Alice' but instead of 'About Bob' I see 'Home'
![pic](http://i.imgur.com/bw61zAi.png)

Here is a sample repo that reproduce this issue:
https://github.com/oren/svelte-router-example-test/blob/1dca6e57a9e88a736ddee727f7f45b6832ad83bf/src/App.html

**Comment by Andorbal** [comment]
Looks like this is an issue with Svelte: https://github.com/sveltejs/svelte/issues/231

**Comment by oren** [comment]
Thanks!

**Comment by PaulBGD** [comment]
Yep! I'm currently looking into it and hopefully I can get a PR open by the weekend.
